code/mybooks/books/urls.py
from django.urls import path
from . import views 

app_name = 'books'
urlpatterns = [
    # /books/       (index.html) - 메인 화면
    path('', views.BooksModelView.as_view(), name='index'), 

    # /books/book/  (book_list.html) - 도서 목록 화면
    path('book/', views.BookList.as_view(), name='book_list'),
    
    # /books/book/10    (book_detail.html) - 도서 상세 화면
    path('book/<int:pk>', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/    (author_list.html) - 저자 목록 화면
    path('author/', views.AuthorList.as_view(), name='author_list'),
    
    # /books/author/10  (author_detail) - 저자 상세 화면
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher  (publisher_list.html) - 출판사 목록 화면
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),     
    
    # /books/publisher/10   (publisher_detail.html) - 출판사 상세 화면
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail')
]

code/mybooks/mybooks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls'))
]

code/mybooks/books/models.py
from django.db import models

# Create your models here.
# Book 테이블
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author') # M:N 관계
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateTimeField()
    # models.ManyToManyField('참조테이블')
    # - 다대다(M:N)의 관계로 필드를 설정
    
    # models.ForeignKey('참조테이블', 옵션)
    # - Book(N) : Publisher(1) 관계로 필드를 설정
    
    def __str__(self):
        return self.title
    
# Author 테이블
class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)   # 인사말
    email = models.EmailField()
    
    def __str__(self):
        return self.name
    
# Publisher 테이블
class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()
    
    def __str__(self):
        return self.name

code/mybooks/books/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView

from .models import Book, Author, Publisher

# Create your views here.
# 장고의 제네릭 뷰
'''
    TemplateView    : 템플릿(화면)을 지정하고 렌더링
    ListView        : 조건에 맞는 여러 개의 객체를 보여줌
                    * ListView 를 상속받으면, model 로 지정한 객체를
                      리스트로 구성하여 context 변수로 템플릿에 넘겨줌
    DetailView      : 특정 개체 하나를 컨텍스트 변수에 담아서 템플릿 넘겨줌
'''
class BooksModelView(TemplateView):
    # 템플릿 지정
    template_name = 'books/index.html'
    
    # 컨텍스트 지정
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        # context['model_list'] = ['Book']
        return context
    
# 도서 목록
class BookList(ListView):
    model = Book
    
    
# 도서 상세
class BookDetail(DetailView):
    model = Book
    
# 저자 목록
class AuthorList(ListView):
    model = Author

# 저자 상세
class AuthorDetail(DetailView):
    model = Author

# 출판사 목록
class PublisherList(ListView):
    model = Publisher
    
# 출판사 상세
class PublisherDetail(DetailView):
    model = Publisher

code/mybooks/books/templates/books/author_detail.html
<h1>저자명 : {{ object.name }}</h1>

<ul>
    <li>인사말 : {{ object.salutation }}</li>
    <li>이메일 : {{ object.email }}</li>
</ul>

code/mybooks/books/templates/books/author_list.html
<h2>저자 목록</h2>

<ul>
    {% for author in object_list %}
        <li>
            <a href="{% url 'books:author_detail' author.id %}">
                {{ author.name }}
            </a>
        </li>
    {% endfor %}
</ul>

code/mybooks/books/templates/books/book_detail.html
<h1>{{ object.title }}</h1>

<ul>
    <li>저자 :
        {% for author in object.authors.all %}
            {{ author }}
            {% if not forloop.last %} ,
            {% else %}
            {% endif %}
        {% endfor %}
    </li>
    <li>출판사 : {{ object.publisher }} </li>
    <li>출판일자 : {{ object.publication_date }}</li>
</ul>

code/mybooks/books/templates/books/book_list.html
<h2>도서 목록</h2>
<ul>
    {% for book in object_list %}
        <li>
            <a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a>
        </li>
    {% endfor %}
</ul>

code/mybooks/books/templates/books/index.html
<h2>도서 관리 시스템</h2>
<ul>
    {% for modelname in model_list %}
        {% comment %}
        lower 필터  : 소문자로 변환
        add 필터    : 문자열을 연결하는 필터
        {% endcomment %}
        
        {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}   
            <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>

code/mybooks/books/templates/books/publisher_detail.html
<h1>출판사명 : {{ object.name }}</h1>

<ul>
    <li>주소 : {{ object.address }}</li>
    <li>웹사이트 : {{ object.website }}</li>
</ul>

code/mybooks/books/templates/books/publisher_list.html
<h2>출판사 목록</h2>

<ul>
    {% for publisher in object_list %}
        <li>
            <a href="{% url 'books:publisher_detail' publisher.id %}">
                {{ publisher.name }}
            </a>
        </li>

    {% endfor %}
</ul>