code/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

'''
    path( 'url', view, name )
    - route(url) : URL 패턴을 정의
    - view : URL 패턴과 일치하는 경우 호출하는 함수
    - name : URL 패턴에 대한 이름 정의
            * 템플릿이나 뷰에서 해당 URL 을 참조하는 이름으로 사용
            
    include('앱.urls')
    - 하위 애플리케이션의 urls.py 파일을 등록하여, 전체 요청경로를 매핑
    
'''

code/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ""(루트) 경로 요청, views.py 파일의 index 함수 호출
    # name="경로 이름"
    # http://localhost:8000/polls  -->  index() 
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),           # /polls/10
    path("<int:question_id>/vote", views.vote, name="vote"),           # /polls/10/vote
    path("<int:question_id>/results/", views.results, name="results"),  # /polls/10/results
    
]

'''
    path("<int:question_id>/", ... )
    - polls/10
    : 10 이라는 데이터를 요청변수 int타입의 question_id 로 연결해준다.
'''

code/mysite/polls/models.py
from django.db import models

# Create your models here.
# 데이터 모델을 정의
# class 로 정의

# 설문
# 질문 제목, 작성 일자
class Question(models.Model):

    def __str__(self):
        return self.question_text           # 관리자 페이지 목록에 출력될 이름

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    sum = models.IntegerField(default=0)
    

# 답변
# 답변 내용, 투표 수
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # ForeignKey( 참조할 테이블, on_delete=옵션 )
    # - Question 테이블의 데이터 삭제 시, 종속된 Choice 테이블에 데이터도 같이 삭제

code/mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
# from django.core.urlresolvers import reverse
from django.urls import reverse

from polls.models import Question, Choice

# Create your views here.
# 설문 목록 뷰
def index(request):
    # return HttpResponse('Hello')
    # 설문 목록을 조회
    question_list = Question.objects.all()  # Question 테이블의 전체목록
    
    # 투표수 합계
    for q in question_list:
        print( q.choice_set.all() )
        choice_list = q.choice_set.all()
        sum = 0
        for c in choice_list:
            sum = sum + c.votes
            print(c.votes)
        q.sum = sum
        
        
        
    context = {'question_list' : question_list}
    return render(request, 'polls/index.html', context)


# 설문 뷰
def detail(request, question_id):
    # question_id 로 데이터 조회
    # SELECT * FROM question WHERE question_id = ?
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question }
    # 응답할 템플릿을 지정 (detail.html)
    return render(request, 'polls/detail.html', context)
    # render()
    # : 요청객체(request)를 지정해주고, 응답할 화면을 지정
    #  HttpResponse 객체를 반환
    #   - 클라이언트에게 응답할 내용
    #   - 화면을 렌더링한 결과 포함
    # get_object_or_404()
    # - get_object_or_404( 테이블명, pk= ? )
    #   --> pk 가 ? 인 데이터를 조회
    #   --> 데이터가 존재하지 않으면, 404 페이지로 이동(HTTP404 예외 발생)
    
    
# 설문 선택 등록
def vote(request, question_id):
    print(f'question_id : {question_id}')
    # 설문 정보 조회
    question = get_object_or_404(Question, pk=question_id)
    
    try:
        # 선택 항목 조회
        choice_id = request.POST['choice']
        # SELECT * FROM choice WHERE choice_id = ?
        selected_choice = question.choice_set.get(pk=choice_id)
        # Choice 테이블에서 데이터 조회
        # request.POST['choice']  : POST 방식으로 요청된 요청변수 choice
    except (KeyError, Choice.DoesNotExist):
        # choice_id 가 없는 경우, --> detail.html 로 돌아가기
        context = {'question' : question, 'error_message' : '항목을 선택해주세요.'}
        return render(request, 'polls/detail.html', context)
    else:
        # UPDATE choice SET votes = votes + 1 WHERE choice_id = ?
        selected_choice.votes += 1      # 투표수 1 증가
        selected_choice.save()          # 데이터 저장
        
        # 투표 결과 화면으로 이동
        # polls/10/results 경로로, results, args=경로속성값을 반대로 매핑하여 출력
        return HttpResponseRedirect( reverse('polls:results', args=(question.id, )) )

    # reverse( '경로 패턴', args=튜플)
    # - args : 경로에 매핑할 변수를 튜플 지정
    
# 리스트 []
# 튜플 ()
# 세트 {}
# 딕셔너리 { a : b }


# 설문 결과 뷰
def results(request, question_id):
    # 설문 테이블 조회
    question = get_object_or_404(Question, pk=question_id)
    
    # results.html 페이지
    return render(request, 'polls/results.html', { 'question' : question} )
    
    
    

    
    
    

code/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<!--
    {% comment %}
        {% url 'polls:vote' question.id %}
        {% url '앱이름:경로이름' 요청변수의 값 %}
        {% url %} 태그는 urls.py 파일을 참조하여, 매핑한 url 경로를 출력해준다urls.py
        * 앱이이름을 사용하려면, urls.py 파일에서 app_name 변수를 설정해야한다.
        앱이름: 경로이름 -> /polls/10/vote
    {% endcomment %}
-->
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<!--
    {% comment %}
        Cross Site Request Forgeries
        : 사이트간 요청 변조하는 공격
        {% csrf_token %} : CRSF 공격을 방지하기 위한 보안 코드
        사이트에 접속했을 때, 서버로부터 토큰을 발급받아서
        해당 사이트에 접속한 인증된 사용자만이 요청을 할 수 있도록 함
    {% endcomment %}
-->
<!-- 설문 - 답변항목 -->
{% for choice in question.choice_set.all %} 
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" 
           value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}" >{{ choice.choice_text }}</label> <br>
{% endfor %}

{% if error_message %}  
<p style="color: red;">{{ eroor_message }}</p>
{% endif %}

<input type="submit" value="투표하기">
<a href="/polls/{{ question.id }}/results">결과보기</a>

</form>

code/mysite/polls/templates/polls/index.html
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li>
                <a href="/polls/{{ question.id }}">{{ question.question_text }}</a>
                <sapn> 투표 수 : {{ question.sum }}</span>
            </li>
            
        {% endfor %}
    </ul>
{% else %}
    <p>조회된 데이터가 없습니다.</p>
{% endif %}

code/mysite/polls/templates/polls/results.html
<h1>결과 화면</h1>

<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} 개</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">다시 투표하기</a>
{% comment %} 
    {% url 'polls:detail' question.id %}  
    {% url '앱이름:경로이름' question.id %}
    - 앱이름    : urls.py 에서 설정한 app_name="polls"
    - 경로이름  : path( name="detail" )
    
    * url 은 urls.py 에 설정된 앱이름:경로이름을 지정하는 키워드

{% endcomment %}