code/myboard/board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    # 게시글
    # 게시글 목록 - '/board/
    path('', views.BoardList.as_view(), name='board_list'),

    # 게시글 조회 - '/board/10'
    path('<int:pk>', views.BoardDetail.as_view(), name='board_detail'),

    # 게시글 쓰기 - '/board/insert
    path('insert/', views.BoardInsert.as_view(), name='board_insert'),
    
    # 게시글 수정 - '/board/update
    path('update/<int:pk>', views.BoardUpdate.as_view(), name='board_update'),
    
    # 게시글 삭제 - '/board/delete
    path('delete/<int:pk>', views.BoardDelete.as_view(), name='board_delete'),
    
]

code/myboard/config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('board/', include('board.urls')),

    
]

code/myboard/board/models.py
from django.db import models

# Create your models here.
# 게시글
# - 제목, 내용
class Board(models.Model):
    title = models.CharField('제목',max_length=100)
    content = models.TextField('내용')

    def __str__(self):
        return self.title

# 댓글
# - 댓글 내용, 외래키(게시글)
class Comment(models.Model):
    content = models.TextField('댓글 내용')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.board.title} - 댓글(id: {self.id})'
    
    
    

code/myboard/board/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from .models import *

# Create your views here.
# 게시글 목록
class BoardList(ListView):
    model = Board
    
    
# 게시글 상세    
class BoardDetail(DetailView):
    model = Board
    
    
# 게시글 쓰기
class BoardInsert(TemplateView):
    template_name = 'board/board_insert.html'
    
    def post(self, request):
        # 요청 메시지의 title, content 가져오기
        title = request.POST.get('title')
        content = request.POST.get('content')
        # Board 모델에 데이터 저장
        
        board = Board(title=title, content=content)
        board.save()
        
        # 게시글 목록으로 이동
        return redirect('/board')
    
# 게시글 수정
class BoardUpdate(View):    
    # get
    def get(self, request, pk):
        board = get_object_or_404(Board, pk=pk)
        context = {'board': board}   
        return render(request, 'board/board_update.html', context)
    
    # post
    def post(self, request, pk):
        # 요청 메시지의 title, content 가져오기
        title = request.POST.get('title')
        content = request.POST.get('content')
        id = self.request.POST.get('board_id')
        board = get_object_or_404(Board, pk=id)
        
        # 게시글 수정
        board.title = title
        board.content = content
        board.save()
        
        # 게시글 목록으로 이동
        return redirect('/board')
    
    
# 게시글 삭제
class BoardDelete(View):
    
    # post
    def post(self, request, pk):
        board = get_object_or_404(Board, pk=pk)
        
        # 게시글 삭제
        board.delete()
        
        return redirect('/board')

code/myboard/config/views.py
from django.shortcuts import render

# 메인 화면
def index(request):
    return render(request, 'index.html')

code/myboard/board/templates/board/board_detail.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ object.title }}</h2>
    <p>
        {{ object.content }}
    </p>

    <a href="{% url 'board:board_update' object.id %}">수정</a>
    <!-- 댓글 목록 -->
{% endblock %}

code/myboard/board/templates/board/board_insert.html
{% extends 'base.html' %}
{% block content %}
    <h1>게시글 쓰기</h1>
    <div class="content">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="input-box">
                <label for="title">제목</label>
                <input type="text" name="title" id="title">
            </div>
            <div class="input-box">
                <label for="content">내용</label>
                <textarea name="content" id="content" cols="30" rows="10"></textarea>
            </div>

            <button type="submit" class="btn">등록</button>
        </form>
    </div>

{% endblock %}

code/myboard/board/templates/board/board_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>게시글 목록</h1>
    <a href="/board/insert">글쓰기</a>
    <ul>
        {% for board in object_list %}
            <li>
                <h3>
                    <a href="{% url 'board:board_detail' board.id %}">
                    {{ board.title }}
                    </a>

                </h3>
                <p>{{ board.content }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

code/myboard/board/templates/board/board_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>게시글 수정</h1>
    <div class="content">
        <form action="" method="POST" id="form">
            {% csrf_token %}
            <input type="hidden" name="board_id" value="{{ board.id }}"
                    id="board_id">
            
            <div class="input-box">
                <label for="title">제목</label>
                <input type="text" name="title" id="title" value="{{ board.title }}">
            </div>
            <div class="input-box">
                <label for="content">내용</label>
                <textarea name="content" id="content" cols="30" rows="10">{{ board.content }}</textarea>
            </div>

            <button type="submit" class="btn">수정</button>
            <button type="button" class="btn" id="btn-delete">삭제</button>
        </form>
    </div>

    <script>
        $(function() {

            $('#btn-delete').on('click', function() {
                // alert('삭제 요청')
                let form = $('#form')
                let board_id = $('#board_id').val()
                form.attr('action', '/board/delete/' + board_id)
                form.submit()       // 폼 제출

            })

        })
    </script>

{% endblock %}

code/myboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Temp</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
</head>
<body>
    <header>
        <!-- <h1>헤더</h1> -->
        <ul>
            <li><a href="/board">게시판</a></li>
        </ul>
    </header>

    <div class="content">
        {% block content %}{% endblock %}
        {% comment %}
           {% block %} : block 템플릿으로 템플릿 상속과 확장 기능을 구현
           - 부모 템플릿에서 자식 템플릿으로 컨텐츠를 전달하는 역할
           * 부모 템플릿에서는 block 으로 특정 부분 지정
           * 자식 템플릿에서는 지정된 부분에 컨텐츠 확장(추가)
        {% endcomment %}
    </div>

    <footer>
        <p>푸터</p>
    </footer>

</body>
</html>

code/myboard/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>Hello Django~!</h2>
    <p>home.utml</p>
{% endblock %}